os: linux

dist: bionic

addons:
  apt:
    packages:
      # required to build
      - cm-super
      - texlive
      - texlive-lang-cyrillic
      - texlive-science
      - texlive-latex-extra
      - latexmk
      - curl

before_install:
    # display Ubuntu version
    lsb_release -a

install:
    # download a newer latexmk
    - curl https://ctan.mirror.norbert-ruehl.de/support/latexmk.zip -o /tmp/latexmk.zip
    - unzip /tmp/latexmk.zip latexmk/latexmk.pl

script:
    make LATEXMK="./latexmk/latexmk.pl" LATEXMK_FLAGS="-Werror"

before_deploy:
    # rename the pdf file
    - cp main.pdf bulatov.pdf
    # set up git user name and tag this commit
    - git config --local user.name "travis"
    - git config --local user.email "travis"
    - export TRAVIS_TAG=latest
    - git tag -f $TRAVIS_TAG

deploy:
  provider: releases
  token:
    secure: "ngPboTrG5Z0D9ke4o9p0RmBJe2uDgcM+ufhR3kvy4z1S6zIoLYaPSLdMCCfHDn4qZft8lrt3Lb/RMaxFGI0fYhS2odna7OaHo0MnTmqeIRpu5w1AIkojbQdsJHA7+CYxCwS72VijOHnj0puPK024RujUIGOPb8caDgvPZ/AV0os8PQKMrGpybhCPj7P2hl8XjvKhycF+Od8zK/m/ERjB/y6PmZ97pvHZYlRykKTLfkPnsnvYynULZP7EyTuGnihXxL0BISn6jntUF0/LdbPmy3D+TVcdnLtS3Cx5KW/vRdS3lmL+whL8BM3T0zbBjdi93EPvOLrmW0YHKiBqamXlxPCcP80hnxmqFz9HgAlJO/mFkWhFCklqhLaINbAlGha1RXOUGv/If+oSSfFcZb9RggSqq56Uap6GfFlvqPTwA/haOMsQ73JVsUOa/Od/tHjK5/iUOaiDb2Ut7n2ao27/ripYbky1gvKmhpZfuz2GAFP1hYwV8oz/AJCV2aB96meYv/sY+h/ZkMWI8KViH/r/ozCS7cq3t+6YIIHUOB/2LEEHMFkFuLH+tkWGTeLBktcpe3sQ2ArHdySd7sG+8LPDvMB7YKF11YSG7r8xoKk4duIodwogm6R6w54bU+sLCnhOkF41fZ5YCH9EoYep3wpufsiQutace1zKi7c2uk8+qaM="
  file:
    - "bulatov.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master

tags:
  except:
    - latest
