os: linux

dist: bionic

addons:
  apt:
    packages:
      # required to build
      - cm-super
      - texlive
      - texlive-lang-cyrillic
      - texlive-science
      - texlive-latex-extra
      - latexmk
      - curl

before_install:
    # display Ubuntu version
    lsb_release -a

install:
    # download a newer latexmk
    - curl https://ctan.mirror.norbert-ruehl.de/support/latexmk.zip -o /tmp/latexmk.zip
    - unzip /tmp/latexmk.zip latexmk/latexmk.pl

script:
    make LATEXMK="./latexmk/latexmk.pl" LATEXMK_FLAGS="-Werror"

before_deploy:
    # rename the pdf file
    - cp main.pdf bulatov.pdf
    # set up git user name and tag this commit
    - git config --local user.name "travis"
    - git config --local user.email "travis"
    - export TRAVIS_TAG=latest
    - git tag -f $TRAVIS_TAG

deploy:
  provider: releases
  token:
    secure: "FIDuqa1FTaKeBWlEHn3g0Z/eUxsMgTCFXl9ahOl1Tnnfq9/jDZgWMLveADs8OG2TAASuNXlg5BogGRiZ50prTUxVgyE5w6aWJEZd9cVz/ljC1+0n+tVfhhntUvW3iTU4j+PqRCBo2wsLGND4qaYKI+UMZuNx2oCHgqBou8OC3o9VeXA1SSDu+31Q8+7rS3ZiXNj75deBOtP6BLf/uHCzNM2y62yLHoP/stR+ZWz+NSdxtACnAjR04PvbngIl15dUWJTHK4DydW17CrKq8qXzp1VNjYfGX2XjEK8dR0NAbwQiD7oVqF1qV1fBLZtaPAA8DfMIcL+MWkE15PcLxjoiUXxlxcDjwSwxZIXfo0NoA1JimmublhBsEqh9fosMfjGCScRZ/L/jUOhglGGgcjSYZe8wQajb7iDggkDbgl6GjJzgrk13k+Nh5leyWasJnRDbIihUZZ43H0QQkyA+iNnIyebtpgbjuE4n7+q3UBN1YVU/CiBrMgY6UQc7J5Cdn+UdH0TCrPzbqhgcK0J5X08o/bfWZUIpx/7Ku/eJwvVCqF1Fxd6hVHTl90tVarm3oGK/shDiXgQL5e/QBNZ1LUjMl/u2mvhVqAdRaU04XA5ZNgEAe6el7sE5w4YXGmomSXzMYsaZEn4RnFIA9vBZUEeI72C4lDprIKHjwquqqxTyASk="
  file:
    - "bulatov.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master

tags:
  except:
    - latest
