os: linux
dist: xenial

language: custom

addons:
  apt:
    packages:
      - texlive
      - texlive-lang-cyrillic
      - texlive-science
      - texlive-latex-extra
      - latexmk

script:
    make
