os: linux
dist: xenial

language: tex

addons:
  apt:
    packages:
      - cm-super
      - texlive
      - texlive-lang-cyrillic
      - texlive-science
      - texlive-latex-extra
      - latexmk

script:
    make
