os: linux

dist: bionic

addons:
  apt:
    packages:
      # required to build
      - cm-super
      - texlive
      - texlive-lang-cyrillic
      - texlive-science
      - texlive-latex-extra
      - latexmk
      - curl

before_install:
    # display Ubuntu version
    lsb_release -a

install:
    # download a newer latexmk
    - curl https://ctan.mirror.norbert-ruehl.de/support/latexmk.zip -o /tmp/latexmk.zip
    - unzip /tmp/latexmk.zip latexmk/latexmk.pl

script:
    make LATEXMK="./latexmk/latexmk.pl" LATEXMK_FLAGS="-Werror"

before_deploy:
    # rename the pdf file
    - cp main.pdf bulatov.pdf
    # set up git user name and tag this commit
    - git config --local user.name "travis"
    - git config --local user.email "travis"
    - export TRAVIS_TAG=latest
    - git tag -f $TRAVIS_TAG

deploy:
  provider: releases
  token:
    secure: "QgOej5Uagzb60IEN+lZ7PmAU9sViwgp1jjLH8bT786zIkIcanqxR4x1CwI0I5Xduty7q7ixsrkuTvqj/sCj+YkWOyP19MoWMw3mFi5fT2uJ+az22HoZIOK2C5BE8u+EMadugwut8RN5kSGahmmpLKB+vwXnAXZHaHS4QPRZbQWmsHJ4Ah3sY3iXwbOe4G8BUSJ/PnZZYTRop4z+don8KMo+hEot811D5+SKsj1DI/aRhHeURJA7CH50YEqo//R1zCTv8C8JJa9CA/ctesFZh0NNAHzff++a1NJM1TTlGwlQnG7hThuBPWTWMUBuToAMz2sNnGthydWl+uTX5TNVNN9uqL8/fz3n1ic0kOVKjDWWjHEXkVLe2JUE0VQ6hO/R4Cs5XS8cbcd5xQALIFJbDCrerexTRXcnweH8uVkNlWYDNO5Z5ukU1graY3/O9aQTd7eszWzOIiBEnS08B4tI7A6xLdwxlMlP8WHw9M0eDKUadyUs0I5ETaOL5xN/PMKHr6sXmFH9vUf2ppOI+VFSOyMC+2TJZv+hAPtLJkslPahhe1UMCr8Ab2hsa45UNkKS3d5FQ8A25mesX32l4qZeotBOK5/Bm1LNzjBKTJGJ3WOF/KBXPDFcTf+1YPxur9ggs8zM1EZaWROUvAX4WaIzVqb8L6QLZE+ni2/gsAKGpolc="
  file:
    - "bulatov.pdf"
  skip_cleanup: true
  overwrite: true
  on:
    branch: master

tags:
  except:
    - latest
